spring:
  cloud:
    stream:
      bindings:
        amsginput:
          destination: a-topic
        amsgoutput:
          destination: a-topic
        amsgcallbackinput:
          destination: acallback-topic
        amsgcallbackoutput:
          destination: acallback-topic
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: onez
    password: onez123
dev: iloveyou
